//This file is automatically generated by generator.lua from https://github.com/cimgui/cimguizmo
//based on ImGuizmo.h file version  1.84 WIP from https://github.com/CedricGuillemet/ImGuizmo
#include "imgui.h"
#include "imgui_internal.h"
#include "./ImGuizmo/ImGuizmo.h"
#include "./ImGuizmo/ImSequencer.h"
#include "cimguizmo.h"



CIMGUI_API void ImGuizmo_SetDrawlist(ImDrawList* drawlist)
{
    return ImGuizmo::SetDrawlist(drawlist);
}
CIMGUI_API void ImGuizmo_BeginFrame()
{
    return ImGuizmo::BeginFrame();
}
CIMGUI_API void ImGuizmo_SetImGuiContext(ImGuiContext* ctx)
{
    return ImGuizmo::SetImGuiContext(ctx);
}
CIMGUI_API bool ImGuizmo_IsOver_Nil()
{
    return ImGuizmo::IsOver();
}
CIMGUI_API bool ImGuizmo_IsUsing()
{
    return ImGuizmo::IsUsing();
}
CIMGUI_API void ImGuizmo_Enable(bool enable)
{
    return ImGuizmo::Enable(enable);
}
CIMGUI_API void ImGuizmo_DecomposeMatrixToComponents(const float* matrix,float* translation,float* rotation,float* scale)
{
    return ImGuizmo::DecomposeMatrixToComponents(matrix,translation,rotation,scale);
}
CIMGUI_API void ImGuizmo_RecomposeMatrixFromComponents(const float* translation,const float* rotation,const float* scale,float* matrix)
{
    return ImGuizmo::RecomposeMatrixFromComponents(translation,rotation,scale,matrix);
}
CIMGUI_API void ImGuizmo_SetRect(float x,float y,float width,float height)
{
    return ImGuizmo::SetRect(x,y,width,height);
}
CIMGUI_API void ImGuizmo_SetOrthographic(bool isOrthographic)
{
    return ImGuizmo::SetOrthographic(isOrthographic);
}
CIMGUI_API void ImGuizmo_DrawCubes(const float* view,const float* projection,const float* matrices,int matrixCount)
{
    return ImGuizmo::DrawCubes(view,projection,matrices,matrixCount);
}
CIMGUI_API void ImGuizmo_DrawGrid(const float* view,const float* projection,const float* matrix,const float gridSize)
{
    return ImGuizmo::DrawGrid(view,projection,matrix,gridSize);
}
CIMGUI_API bool ImGuizmo_Manipulate(const float* view,const float* projection,OPERATION operation,MODE mode,float* matrix,float* deltaMatrix,const float* snap,const float* localBounds,const float* boundsSnap)
{
    return ImGuizmo::Manipulate(view,projection,operation,mode,matrix,deltaMatrix,snap,localBounds,boundsSnap);
}
CIMGUI_API void ImGuizmo_ViewManipulate_Float(float* view,float length,ImVec2 position,ImVec2 size,ImU32 backgroundColor)
{
    return ImGuizmo::ViewManipulate(view,length,position,size,backgroundColor);
}
CIMGUI_API void ImGuizmo_ViewManipulate_FloatPtr(float* view,const float* projection,OPERATION operation,MODE mode,float* matrix,float length,ImVec2 position,ImVec2 size,ImU32 backgroundColor)
{
    return ImGuizmo::ViewManipulate(view,projection,operation,mode,matrix,length,position,size,backgroundColor);
}
CIMGUI_API void ImGuizmo_SetID(int id)
{
    return ImGuizmo::SetID(id);
}
CIMGUI_API bool ImGuizmo_IsOver_OPERATION(OPERATION op)
{
    return ImGuizmo::IsOver(op);
}
CIMGUI_API void ImGuizmo_SetGizmoSizeClipSpace(float value)
{
    return ImGuizmo::SetGizmoSizeClipSpace(value);
}
CIMGUI_API void ImGuizmo_AllowAxisFlip(bool value)
{
    return ImGuizmo::AllowAxisFlip(value);
}
CIMGUI_API void SequenceInterface_BeginEdit(SequenceInterface* self,int noname1)
{
    return self->BeginEdit(noname1);
}
CIMGUI_API void SequenceInterface_EndEdit(SequenceInterface* self)
{
    return self->EndEdit();
}
CIMGUI_API int SequenceInterface_GetItemTypeCount(SequenceInterface* self)
{
    return self->GetItemTypeCount();
}
CIMGUI_API const char* SequenceInterface_GetItemTypeName(SequenceInterface* self,int noname1)
{
    return self->GetItemTypeName(noname1);
}
CIMGUI_API const char* SequenceInterface_GetItemLabel(SequenceInterface* self,int noname1)
{
    return self->GetItemLabel(noname1);
}
CIMGUI_API const char* SequenceInterface_GetCollapseFmt(SequenceInterface* self)
{
    return self->GetCollapseFmt();
}
CIMGUI_API void SequenceInterface_Add(SequenceInterface* self,int noname1)
{
    return self->Add(noname1);
}
CIMGUI_API void SequenceInterface_Del(SequenceInterface* self,int noname1)
{
    return self->Del(noname1);
}
CIMGUI_API void SequenceInterface_Duplicate(SequenceInterface* self,int noname1)
{
    return self->Duplicate(noname1);
}
CIMGUI_API void SequenceInterface_Copy(SequenceInterface* self)
{
    return self->Copy();
}
CIMGUI_API void SequenceInterface_Paste(SequenceInterface* self)
{
    return self->Paste();
}
CIMGUI_API size_t SequenceInterface_GetCustomHeight(SequenceInterface* self,int noname1)
{
    return self->GetCustomHeight(noname1);
}
CIMGUI_API void SequenceInterface_DoubleClick(SequenceInterface* self,int noname1)
{
    return self->DoubleClick(noname1);
}
CIMGUI_API void SequenceInterface_CustomDraw(SequenceInterface* self,int noname1,ImDrawList* noname2,const ImRect noname3,const ImRect noname4,const ImRect noname5,const ImRect noname6)
{
    return self->CustomDraw(noname1,noname2,noname3,noname4,noname5,noname6);
}
CIMGUI_API void SequenceInterface_CustomDrawCompact(SequenceInterface* self,int noname1,ImDrawList* noname2,const ImRect noname3,const ImRect noname4)
{
    return self->CustomDrawCompact(noname1,noname2,noname3,noname4);
}
CIMGUI_API SequenceInterface* ImSequencer_CreateSequencerInterface(const SequenceInterfaceVTable table)
{
    return ImSequencer::CreateSequencerInterface(table);
}
CIMGUI_API void ImSequencer_DestroySequenceInterface(SequenceInterface* ptr)
{
    return ImSequencer::DestroySequenceInterface(ptr);
}
CIMGUI_API bool ImSequencer_Sequencer(SequenceInterface* sequence,int* currentFrame,bool* expanded,int* selectedEntry,int* firstFrame,int sequenceOptions)
{
    return ImSequencer::Sequencer(sequence,currentFrame,expanded,selectedEntry,firstFrame,sequenceOptions);
}



