//This file is automatically generated by generator.lua from https://github.com/cimgui/cimguizmo
//based on ImGuizmo.h file version  1.84 WIP from https://github.com/CedricGuillemet/ImGuizmo
#ifndef CIMGUIZMO_INCLUDED
#define CIMGUIZMO_INCLUDED

#include "cimgui.h"

#ifdef CIMGUI_DEFINE_ENUMS_AND_STRUCTS

typedef struct ImDrawList ImDrawList;
typedef struct ImRect ImRect;
typedef enum {
      TRANSLATE_X = (1u << 0),
      TRANSLATE_Y = (1u << 1),
      TRANSLATE_Z = (1u << 2),
      ROTATE_X = (1u << 3),
      ROTATE_Y = (1u << 4),
      ROTATE_Z = (1u << 5),
      ROTATE_SCREEN = (1u << 6),
      SCALE_X = (1u << 7),
      SCALE_Y = (1u << 8),
      SCALE_Z = (1u << 9),
      BOUNDS = (1u << 10),
      SCALE_XU = (1u << 11),
      SCALE_YU = (1u << 12),
      SCALE_ZU = (1u << 13),
      TRANSLATE = TRANSLATE_X | TRANSLATE_Y | TRANSLATE_Z,
      ROTATE = ROTATE_X | ROTATE_Y | ROTATE_Z | ROTATE_SCREEN,
      SCALE = SCALE_X | SCALE_Y | SCALE_Z,
      SCALEU = SCALE_XU | SCALE_YU | SCALE_ZU,
      UNIVERSAL = TRANSLATE | ROTATE | SCALEU
   }OPERATION;
typedef enum {
      LOCAL,
      WORLD
   }MODE;
struct ImDrawList;
struct ImRect;
typedef enum {
      SEQUENCER_EDIT_NONE = 0,
      SEQUENCER_EDIT_STARTEND = 1 << 1,
      SEQUENCER_CHANGE_FRAME = 1 << 3,
      SEQUENCER_ADD = 1 << 4,
      SEQUENCER_DEL = 1 << 5,
      SEQUENCER_COPYPASTE = 1 << 6,
      SEQUENCER_EDIT_ALL = SEQUENCER_EDIT_STARTEND | SEQUENCER_CHANGE_FRAME
   }SEQUENCER_OPTIONS;
typedef struct SequenceInterface SequenceInterface;
struct SequenceInterface
{
      bool focused;
      virtual int GetFrameMin() const;
      virtual int GetFrameMax() const;
      virtual int GetItemCount() const;
      virtual void Get(int index, int** start, int** end, int* type, unsigned int* color);
       virtual ~SequenceInterface();
};
typedef struct SequenceInterfaceVTable SequenceInterfaceVTable;
struct SequenceInterfaceVTable
{
      int(*GetItemTypeCount)(void* userdata);
      const char* (*GetItemTypeName)(int typeIndex, void* userdata);
      const char* (*GetItemLabel)(int index, void* userdata);
      const char* (*GetCollapseFmt)(void* userdata);
      void (*Get)(int index, int** start, int** end, int* type, unsigned int* color, void* userdata);
      void (*Add)(int type, void* userdata);
      void (*Del)(int index, void* userdata);
      void (*Duplicate)(int index, void* userdata);
      void (*Copy)(void* userdata);
      void (*Paste)(void* userdata);
      void (*DoubleClick)(int index, void* userdata);
      void (*CustomDraw)(int index, ImDrawList* draw_list, const ImRect* rc, const ImRect* legendRect, const ImRect* clippingRect, const ImRect* legendClippingRect, void* userdata);
      void (*CustomDrawCompact)(int index, ImDrawList* draw_list, const ImRect* rc, const ImRect* clippingRect, void* userdata);
      void* userdata;
};
#else
#endif // CIMGUI_DEFINE_ENUMS_AND_STRUCTS

#ifndef CIMGUI_DEFINE_ENUMS_AND_STRUCTS
typedef ImSequencer::SequenceInterface SequenceInterface;
typedef ImSequencer::SequenceInterfaceVTable SequenceInterfaceVTable;
typedef ImGuizmo::MODE MODE;
typedef ImGuizmo::OPERATION OPERATION;
typedef ImSequencer::SEQUENCER_OPTIONS SEQUENCER_OPTIONS;
#endif //CIMGUI_DEFINE_ENUMS_AND_STRUCTS
CIMGUI_API void ImGuizmo_SetDrawlist(ImDrawList* drawlist);
CIMGUI_API void ImGuizmo_BeginFrame(void);
CIMGUI_API void ImGuizmo_SetImGuiContext(ImGuiContext* ctx);
CIMGUI_API bool ImGuizmo_IsOver_Nil(void);
CIMGUI_API bool ImGuizmo_IsUsing(void);
CIMGUI_API void ImGuizmo_Enable(bool enable);
CIMGUI_API void ImGuizmo_DecomposeMatrixToComponents(const float* matrix,float* translation,float* rotation,float* scale);
CIMGUI_API void ImGuizmo_RecomposeMatrixFromComponents(const float* translation,const float* rotation,const float* scale,float* matrix);
CIMGUI_API void ImGuizmo_SetRect(float x,float y,float width,float height);
CIMGUI_API void ImGuizmo_SetOrthographic(bool isOrthographic);
CIMGUI_API void ImGuizmo_DrawCubes(const float* view,const float* projection,const float* matrices,int matrixCount);
CIMGUI_API void ImGuizmo_DrawGrid(const float* view,const float* projection,const float* matrix,const float gridSize);
CIMGUI_API bool ImGuizmo_Manipulate(const float* view,const float* projection,OPERATION operation,MODE mode,float* matrix,float* deltaMatrix,const float* snap,const float* localBounds,const float* boundsSnap);
CIMGUI_API void ImGuizmo_ViewManipulate_Float(float* view,float length,ImVec2 position,ImVec2 size,ImU32 backgroundColor);
CIMGUI_API void ImGuizmo_ViewManipulate_FloatPtr(float* view,const float* projection,OPERATION operation,MODE mode,float* matrix,float length,ImVec2 position,ImVec2 size,ImU32 backgroundColor);
CIMGUI_API void ImGuizmo_SetID(int id);
CIMGUI_API bool ImGuizmo_IsOver_OPERATION(OPERATION op);
CIMGUI_API void ImGuizmo_SetGizmoSizeClipSpace(float value);
CIMGUI_API void ImGuizmo_AllowAxisFlip(bool value);
CIMGUI_API void SequenceInterface_BeginEdit(SequenceInterface* self,int noname1);
CIMGUI_API void SequenceInterface_EndEdit(SequenceInterface* self);
CIMGUI_API int SequenceInterface_GetItemTypeCount(SequenceInterface* self);
CIMGUI_API const char* SequenceInterface_GetItemTypeName(SequenceInterface* self,int noname1);
CIMGUI_API const char* SequenceInterface_GetItemLabel(SequenceInterface* self,int noname1);
CIMGUI_API const char* SequenceInterface_GetCollapseFmt(SequenceInterface* self);
CIMGUI_API void SequenceInterface_Add(SequenceInterface* self,int noname1);
CIMGUI_API void SequenceInterface_Del(SequenceInterface* self,int noname1);
CIMGUI_API void SequenceInterface_Duplicate(SequenceInterface* self,int noname1);
CIMGUI_API void SequenceInterface_Copy(SequenceInterface* self);
CIMGUI_API void SequenceInterface_Paste(SequenceInterface* self);
CIMGUI_API size_t SequenceInterface_GetCustomHeight(SequenceInterface* self,int noname1);
CIMGUI_API void SequenceInterface_DoubleClick(SequenceInterface* self,int noname1);
CIMGUI_API void SequenceInterface_CustomDraw(SequenceInterface* self,int noname1,ImDrawList* noname2,const ImRect noname3,const ImRect noname4,const ImRect noname5,const ImRect noname6);
CIMGUI_API void SequenceInterface_CustomDrawCompact(SequenceInterface* self,int noname1,ImDrawList* noname2,const ImRect noname3,const ImRect noname4);
CIMGUI_API SequenceInterface* ImSequencer_CreateSequencerInterface(const SequenceInterfaceVTable table);
CIMGUI_API void ImSequencer_DestroySequenceInterface(SequenceInterface* ptr);
CIMGUI_API bool ImSequencer_Sequencer(SequenceInterface* sequence,int* currentFrame,bool* expanded,int* selectedEntry,int* firstFrame,int sequenceOptions);


#endif //CIMGUIZMO_INCLUDED




